### ISSUE TITLE
Problem on Installing RTPProxy 

### ISSUE THREAD

**Issue by eliakimfelmorais** [sippy/rtpproxy#105]
Hi Guys,

I checkout the master branch on rtpproxy repository on github and trying to install on centos 7 without sucess.

Commands:
  414  git clone -b master https://github.com/sippy/rtpproxy.git
  419  cd rtpproxy
  420  git submodule update --init --recursive
  421  ./configure
  422  make

Error:

mv -f .deps/execinfo_TEST-stacktraverse.Tpo .deps/execinfo_TEST-stacktraverse.Po
/bin/sh ../libtool  --tag=CC   --mode=link gcc -g3 -O0 -fno-omit-frame-pointer -g -O2   -o execinfo_TEST execinfo_TEST-execinfo.o execinfo_TEST-stacktraverse.o -ldl -lrt
libtool: link: gcc -g3 -O0 -fno-omit-frame-pointer -g -O2 -o execinfo_TEST execinfo_TEST-execinfo.o execinfo_TEST-stacktraverse.o  -ldl -lrt
make[1]: Saindo do diretório `/usr/src/rtpproxy/libexecinfo'
Making all in libucl
make[1]: Entrando no diretório `/usr/src/rtpproxy/libucl'
gcc -DHAVE_CONFIG_H -I. -I../src  -DMODULE_IF_CODE -Dmod_strdup=strdup -DRTPP_MEMDEB_STDOUT -include rtpp_debugon.h -I.. -DMEMDEB_APP=libucl_test -I../external/libucl/include -I../hepconnector -D_DEFAULT_SOURCE -D_ISOC99_SOURCE -DLINUX_XXX -g3 -O0 -fno-omit-frame-pointer -g -O2 -MT libucl_test-libucl_test.o -MD -MP -MF .deps/libucl_test-libucl_test.Tpo -c -o libucl_test-libucl_test.o `test -f 'libucl_test.c' || echo './'`libucl_test.c
In file included from ../src/rtpp_debugon.h:31:0,
                 from <command-line>:0:
../src/rtpp_autoglitch.h:81:69: error: conflicting types for ‘restrict’
 int rtpp_glitch_accept(int, struct sockaddr * restrict, socklen_t * restrict,
                                                                     ^
../src/rtpp_autoglitch.h:81:47: note: previous definition of ‘restrict’ was here
 int rtpp_glitch_accept(int, struct sockaddr * restrict, socklen_t * restrict,
                                               ^
make[1]: ** [libucl_test-libucl_test.o] Erro 1
make[1]: Saindo do diretório `/usr/src/rtpproxy/libucl

S.O : [root@ip-172-31-2-5 rtpproxy]# cat /etc/redhat-release 
CentOS Linux release 7.7.1908 (Core)

Kernel: 3.10.0-957.1.3.el7.x86_64

Thank you.

**Comment by sobomax** [comment]
OK, I'll take a look. Thanks for reporting!

**Comment by sobomax** [comment]
@eliakimfelmorais should be fixed now. Thanks for reporting!
