### ISSUE TITLE
Reserving four RTP ports per session

### ISSUE THREAD

**Issue by amarsou88** [sippy/rtpproxy#107]
Hi guys;
I have a question. Why RtpProxy reseriving four RTP ports for the same session? 
Thank you.
[rtp.log.txt](https://github.com/sippy/rtpproxy/files/4465128/rtp.log.txt)

**Comment by sobomax** [comment]
It needs two support two independent RTP sessions (A->B, B->A) and two
RTCP. Technically you can get number of ports down to just two, by reusing
the same port for both incoming and outgoing call legs, but that would make
NAT traversal much more difficult and unreliable, so for practical reasons
we've settled on a less than ideal usage.

-Max

**Comment by amarsou88** [comment]
Ok, thank you so much.
