### ISSUE TITLE
Get more session per machine

### ISSUE THREAD

**Issue by amarsou88** [sippy/rtpproxy#108]
Hi; 
The problem is that I want to be able to have more free ports to get more users concected on server. Knowing that we spend 4 ports per session and we have 2 sessions this adds up 8 ports, What I think to do is to use two interfaces on the machine and send some trafic to first interface, an som other to the second interface. 
 Thats a good idea?
 I mean, I can use te loopback ip and the interface ip, then I can doble the sessions. 
Did you have a better idea more profesional?
Sorry and thank you.

**Comment by sobomax** [comment]
Hi, having more interfaces totally possible and there are nothing wrong with this approach. Also it could be done either at application level, where you pin sessions to a different IPs, or at the OS level using interface bonding techniques (FEC etc). You can even run a separate RTPProxy instance per interface/IP and load-balance those using features in OpenSIPS/Kamailio.
