### ISSUE TITLE
eaud_crypto.c:156:17: error: ‘srtp_policy_t’ {aka ‘struct srtp_policy_t’} has no member named ‘ekt’

### ISSUE THREAD

**Issue by zizomizo84gh** [sippy/rtpproxy#120]
Hi everyone,

I am trying to install and compile the source of rtpproxy and encountered the error following error after "make clean all":

eaud_crypto.c:156:17: error: ‘srtp_policy_t’ {aka ‘struct srtp_policy_t’} has no member named ‘ekt’

may someone advise please and help with this error ?

I copied the directory of libsrtp into the /usr/local/src/rtpproxy where the sorurce is and installed it againg. Still getting the same error.

my machine is:
Linux T450 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Thanks in advance and best regards

**Comment by sobomax** [comment]
oh, OK, I see, they've removed ekt member. Fix is coming.

**Comment by sobomax** [comment]
Fixed and the fix is merged into rtpp_2_2 branch (which is the only one affected). Thanks for reporting! @zizomizo84gh ❤

**Comment by zizomizo84gh** [comment]
Hi Sobomax,

thanks for your response. I am out and faraway from my machine... I will try it later.

Best regards
