### ISSUE TITLE
acct_rtcp_hep - malformed JSON format in Encapsulated Payload of a Receiver Report

### ISSUE THREAD

**Issue by solarmon** [sippy/rtpproxy#126]
Hi,

As discovered in https://github.com/sipcapture/homer/issues/536 the JSON format of the Encapsulated Payload of a Receiver Report is malformed.

There is a trailing comma character on the last item of the JSON list.

Line 193 doesn't have the comma character:

https://github.com/sippy/rtpproxy/blob/b9d7b4ced2e9797f7d5d3f033af288fbc1aaecd8/modules/acct_rtcp_hep/rtcp2json.c#L193

But line 217 seems to have this comma character:

https://github.com/sippy/rtpproxy/blob/b9d7b4ced2e9797f7d5d3f033af288fbc1aaecd8/modules/acct_rtcp_hep/rtcp2json.c#L217
 
This was causing a display issue in Homer due to the malformed HEP packet. Once the offending comma (from line 217 of rtcp2json.c) was removed (and rtpproxy and modules recompiled) then the issue was resolved.

**Comment by babakyakhchali** [comment]
Thanks @solarmon 
The proposed solution solved my problem too
