### ISSUE TITLE
Resizing works erratically on Linux, causing new forwarding1 test to fail

### ISSUE THREAD

**Issue by sobomax** [sippy/rtpproxy#24]
I am observing resizing to not working at all or behaving erratically on Linux for most of the codecs as compared to the same codecs on FreeBSD. Please see attached files, the stats on top is FreeBSD, the stats on the bottom is Linux. Resizing is done using Uz40/Lz60.

First session (FreeBSD on top, Linux on bottom):
![screenshot321](https://cloud.githubusercontent.com/assets/218662/6178164/510b61a6-b2c1-11e4-8ae4-b70acb769c25.png)

Some extra debug for the first session showing output G.722 packets with different size than the rest (which is why it went down from 3000 packets to 2970):
![screenshot322](https://cloud.githubusercontent.com/assets/218662/6178166/510e3e44-b2c1-11e4-83fb-6bdb458a9ee1.png)

Second session  (FreeBSD on top, Linux on bottom):
![screenshot320](https://cloud.githubusercontent.com/assets/218662/6178165/510ca1ce-b2c1-11e4-8304-bcbdd0ba3978.png)

**Comment by bambyster** [comment]
I cannot reproduce the issue on my Ubuntu 14.04. Everything goes smoothly:
![2015-02-13 17 49 58](https://cloud.githubusercontent.com/assets/10989836/6190277/58492b4a-b3a9-11e4-9a39-63bf2e94cfdb.png)

**Comment by sobomax** [comment]
Fixed.
