### ISSUE TITLE
Create regression / test suite

### ISSUE THREAD

**Issue by sobomax** [sippy/rtpproxy#3]
It would be nice to have easy-to-use and easy-to-extend regression / test suite that would go through all supported commands and verify that each of them performs as expected. In doing so, it can also test various aspects of API, i.e. test that all sippy.Rtp_proxy_client, sippy.Rtp_proxy_client_xxx, sippy.Rtp_proxy_session, are functional and exception-free.

One approach that we can take is to use rtpproxy that is being tested itself to generate/analyze RTP traffic, so successful completion of the test suite would not only means that all commands are processed properly, but that actual RTP is handled correctly.

**Comment by jevonearth** [comment]
Notes for posterity;

The Makefile now has a `test` target that runs the tests located in the tests subdirectory. The test suite is also hooked up to travis, and a private jenkins CI server.

There's also https://github.com/sippy/voiptests which has integration tests for OpenSIPs and Kamailio. 

Closing issue. Feel free to open new issues for specific tests.
