### ISSUE TITLE
`make check` tests Fail

### ISSUE THREAD

**Issue by aftnix** [sippy/rtpproxy#31]
`make check` hangs with many failure--
![image](https://cloud.githubusercontent.com/assets/1655398/8018813/458d5242-0c50-11e5-9e3b-914cf7b180da.png)

I'm on this commit ---

![image](https://cloud.githubusercontent.com/assets/1655398/8018819/87c5c996-0c50-11e5-80c5-539d58481b04.png)

**Comment by albersag** [comment]
Same issue here

make[3]: Entering directory '/usr/src/rtpproxy-2.0.0/tests'
PASS: startstop
PASS: basic_versions
PASS: command_parser
FAIL: makeann
FAIL: extractaudio
PASS: session_timeouts
FAIL: playback1
FAIL: forwarding1
make[4]: Entering directory '/usr/src/rtpproxy-2.0.0/tests'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests'
============================================================================
Testsuite summary for rtpproxy 2.0.beta.20150106
============================================================================
# TOTAL: 8
# PASS:  4
# SKIP:  0
# XFAIL: 0
# FAIL:  4
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to sobomax@sippysoft.com
============================================================================
Makefile:556: recipe for target 'test-suite.log' failed
make[3]: *** [test-suite.log] Error 1
make[3]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests'
Makefile:662: recipe for target 'check-TESTS' failed
make[2]: *** [check-TESTS] Error 2
make[2]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests'
Makefile:784: recipe for target 'check-am' failed
make[1]: *** [check-am] Error 2
make[1]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests'
Makefile:459: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1


cat /etc/debian_version 
8.1

**Comment by sobomax** [comment]
Alberto, you need to have the following dependencies installed to run tests
100%:

- bcg729 (
http://download-mirror.savannah.gnu.org/releases/linphone/plugins/sources/bcg729-1.0.0.tar.gz
)
- libg722 (git://github.com/sippy/libg722)
- libgsm1
- libsndfile1
- tcpdump
- Twisted

Install (use development version), re-run configure and then make all. Hope
it helps. Please let us know if you still experience the issue. Thanks!

-Maxim

On Thu, Jul 2, 2015 at 8:00 AM, albersag <notifications@github.com> wrote:

> Same issue here
>
> make[3]: Entering directory '/usr/src/rtpproxy-2.0.0/tests'
> PASS: startstop
> PASS: basic_versions
> PASS: command_parser
> FAIL: makeann
> FAIL: extractaudio
> PASS: session_timeouts
> FAIL: playback1
> FAIL: forwarding1
> make[4]: Entering directory '/usr/src/rtpproxy-2.0.0/tests'
> make[4]: Nothing to be done for 'all'.
> make[4]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests' Testsuite
> summary for rtpproxy 2.0.beta.20150106 TOTAL: 8 PASS: 4 SKIP: 0 XFAIL: 0 FAIL:
> 4 XPASS: 0 ERROR: 0
>
> See tests/test-suite.log
> Please report to sobomax@sippysoft.com
>
> Makefile:556: recipe for target 'test-suite.log' failed
> make[3]: *** [test-suite.log] Error 1
> make[3]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests'
> Makefile:662: recipe for target 'check-TESTS' failed
> make[2]: *** [check-TESTS] Error 2
> make[2]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests'
> Makefile:784: recipe for target 'check-am' failed
> make[1]: *** [check-am] Error 2
> make[1]: Leaving directory '/usr/src/rtpproxy-2.0.0/tests'
> Makefile:459: recipe for target 'check-recursive' failed
> make: *** [check-recursive] Error 1
>
> cat /etc/debian_version
> 8.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sippy/rtpproxy/issues/31#issuecomment-118059868>.
>



-- 
Maksym Sobolyev
Sippy Software, Inc.
Internet Telephony (VoIP) Experts
Tel (Canada): +1-778-783-0474
Tel (Toll-Free): +1-855-747-7779
Fax: +1-866-857-6942
Web: http://www.sippysoft.com
MSN: sales@sippysoft.com
Skype: SippySoft

**Comment by jevonearth** [comment]
Here's the full list of dependencies for running tests;

- audio/bcg729
- audio/gsm
- audio/libsndfile
- devel/autoconf
- devel/automake
- devel/libtool
- devel/pkgconf
- devel/py-twisted
- libg722 (Available from https://github.com/sippy/libg722)

I added this list to the tests/README.md file.

Closing this issue. If you guys still have failing tests, please open a new issue. Thnx!
