### ISSUE TITLE
each RTP media stream requires four open connections

### ISSUE THREAD

**Issue by hd16861686** [sippy/rtpproxy#32]
-L Adjust the number of simultaneous open connections. Note that each RTP media stream requires four open connections. A SIP call can open more than one RTP media stream depending on the client's setup.
-----can any guys explain me why "each RTP media stream requires four open connections", As I know,each normal audio call have 2 media stream  in different directions, caller-->callee and callee-->caller.
and from the tcpdump capture file I can see each UE in an audio call establish one udp connection to one rtpproxy port,  and UE send rtp stream to the port and received rtp stream from the port. so it means in this audio call, rtpproxy only need open two port to handle the rtp stream.
but this result can not match the description about the "-L" command flag in rtpproxy v2.0.0 Release Notes.

**Comment by hd16861686** [comment]
any one can help me ?

**Comment by razvancrainea** [comment]
Note that each call leg needs both RTP and RCTP. Therefore RTPProxy opens two ports for each client: caller and callee.

**Comment by sobomax** [comment]
This is basically a design decision. We've started with the rtpproxy using
just one port for both ingress and egress rtp streams, but that does not
work very well in the "nated clients" scenarios, where ability to
distinguish traffic from one side from traffic from the other side with
100% reliability is crucial to ensure proper operation of the software.
Sockets are pretty cheap these days, and in practice you can have 50+K
sockets per box (i.e. 10K potential sessions even with a signe IP), while
actual capacity of the box would be limited by the more modest number
something like 3-5K sessions.

On Mon, Aug 17, 2015 at 7:53 AM, Răzvan Crainea <notifications@github.com>
wrote:

> Note that each call leg needs both RTP and RCTP. Therefore RTPProxy opens
> two ports for each client: caller and callee.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sippy/rtpproxy/issues/32#issuecomment-131851015>.
>



-- 
Maksym Sobolyev
Sippy Software, Inc.
Internet Telephony (VoIP) Experts
Tel (Canada): +1-778-783-0474
Tel (Toll-Free): +1-855-747-7779
Fax: +1-866-857-6942
Web: http://www.sippysoft.com
MSN: sales@sippysoft.com
Skype: SippySoft
