### ISSUE TITLE
H264 frame corrupted when using rtpproxy 

### ISSUE THREAD

**Issue by LiohAu** [sippy/rtpproxy#38]
Hello

I am currently making test calls with the baresip client and I have an issue with the video stream. When I make direct LAN calls without using kamailio+rtpproxy the video stream is fine, but when I make the same call with rtpproxy in the middle, I get a lot of H264 decoding errors from baresip. 
I think that the packets are being corrupted by rtpproxy, or maybe some are dropped, I don't really know, but if someone could help me to confirm that rtpproxy is responsible of the issue and to fix the issue, that would be really nice :)

**Comment by sobomax** [comment]
Hi, is it possible for you to take a packet capture of a test call on the machine running rtpproxy and share with us the PCAP file? That would help us to understand the nature of the problem and also could provide data for a test case to test that functionality once the issue has been resolved. Thanks!

**Comment by octocat9lee** [comment]
Hi, I also meet the same problem. The run environment: rtpproxy running 10.0.204.67. I get the lost rtp packet sequence from rtpproxy log, eg update_rtpp_stats: 0x366772D7/8889: delta = 2 (update_rtpp_stats: 0x366772D7/8855: delta = 3)(0x18BE6784/33644: delta = 4)，so I filter the pcap：
`rtp.ssrc == 0x366772D7 and rtp.seq == 8888`，it show received packet from sender, but rtproxy not send the packet to receiver. The pcap file [PCAP file](https://github.com/octocat9lee/tools/blob/master/opensips/rtp_loss.pcap)

**Comment by sobomax** [comment]
Julien,

Thank you for your report. This is sort of well-known defficiency (missing
feature?). The problem with handling video streams is that they have no
fixed PPS, while the RTPProxy forwarding code is optimized to handling
audio streams with fixed PPS rates that are multiple of 10ms and no less
that 10ms. This serves two functions: it gives each session fairly equal
access to forwarding resources preventing one session from jeopardizing
network bandwidth and/or forwarding capacity (helpful with dealing
brain-damaged devices spewing bazillions packets per seconds as well as
certain types of attacks on infrastructure), but it also smoothes out any
irregularities in the incoming RTP stream(s) without using jitter
buffering. As you can see on the attached pictures it does pretty decent
job on that, combing down your very irregular stream to one that has 10ms
spaced apart. At the expense of dropping 40% of all packets of course.

Now, way to fix it in long-term could be adding different type of forwarder
that is event-driven and optimized to handling variable-rate streams.

What you can do in a short-term, however, is to increase max PPS rate from
100 currently to say 1000, that would give you sufficient resolution to
handle this kind of streams, at expense of some extra CPU burnout. This can
be done by changing:

#define      MAX_RTP_RATE    100

to

#define      MAX_RTP_RATE    1000

and then re-compiling the code.

It would be really helpful if you can check if suggested workaround works,
we might then just make it a command-line option and add a manual entry.

-Max
P.S. Please also let me know if it's OK to use your capture as part of our
regression test suite. I am not sure if there any private info in that
video. Thanks!

**Comment by sobomax** [comment]
Hi, the issue should be resolved now in latest master (as of commit e19f56679862e6). It removes PPS limitation allowing both audio and video streams to be correctly processed. I've tested by placing some video calls using H.264 codec at 2mbps and the quality seems to be adequate. The new functionality will be available as part of the next 2.3 (3.0?) release later this year.
