### ISSUE TITLE
Recording Video Calls

### ISSUE THREAD

**Issue by goharahmed** [sippy/rtpproxy#42]
Hi,
I'm using RTPproxy for my setup with all video calls. I want to record the video calls to be saved in disk and converted to mp4 or some video format. 

What are my options, since I can only get audio saved in wav only.

Thanks,
Gohar

**Comment by dexteruk** [comment]
There is currently no support for saving video streams at this time.  I recommend opening a discussion in the mailing list https://groups.google.com/forum/#!forum/rtpproxy

**Comment by sobomax** [comment]
@dexteruk yes and no, you can save video streams into pcap file I think using the "R[ecord]" fuction. There is no build-in way to decode that though. Some external tools might be able to do decoding, but I am not aware of any.
