### ISSUE TITLE
auto fix client ip and port

### ISSUE THREAD

**Issue by zhang90501** [sippy/rtpproxy#50]
My client(behind NAT) first send INVITE request to sip proxy(kamailio) with sdp(use local ip and port), then after session establish complete client know rtpproxy ip(public) and port. So client send its rtp stream to rtpproxy, but rtpproxy found rtp stream comes from another ip and port(NAT public ip and new assigned port). So rtpproxy discard these package. Any way can auto fix map ports with new client ip and port? How can I configure it?

**Comment by sobomax** [comment]
Hi, that scenario should work automatically, unless you are using some extra flags like for example 'A' in the rtppproxy_offer/rtpproxy_answer methods. Would you mind sharing your kamailio configuration that is related to the rtpproxy? Thanks!

**Comment by zhang90501** [comment]
When request coming from client through public network, I just use rtpproxy_manage("ei") to proxy RTP for B2BUA. Then reply using rtpproxy_manage("ie") to proxy for client. Beceause B2BUA and kamailio are at Independent network, and kamailio has two network card that one connect to B2BUA and the other one connect to public network.
I also agree it should work automatically, but as result from my capture packets,  I found rtpproxy always send to port of SDP and client always send from port of NAT assigned. So it didn't switch port automatically.

**Comment by sobomax** [comment]
Thanks, can you clarify options that you start the rtpproxy with then? Thanks!

**Comment by zhang90501** [comment]
Thanks for your help. After I read some rtpproxy source code , I understand it how to auto switch caller/callee ip and port at first time. I didn't use it in a right way.

I didn't understand some other rtpproxy technology detail, can introduce some document to me?
Thanks!
