### ISSUE TITLE
rtpproxy crash

### ISSUE THREAD

**Issue by Rico29** [sippy/rtpproxy#53]
Hello,
I have a problem with rtpproxy which crashes with this message : 

 Feb  8 02:15:26 orange-pa2 rtpproxy[32699]: rtpproxy: rtpp_stats.c:398: rtpp_stats_update_derived: Assertion `dst->last_ts < dtime' failed.
Feb  8 02:15:26 orange-pa2 systemd[1]: rtpproxy-resp-orange.service: main process exited, code=killed, status=6/ABRT
Feb  8 02:15:26 orange-pa2 systemd[1]: Unit rtpproxy-resp-orange.service entered failed state.

I'm running commit 3938d6d41d4b4a2bb93f01d4e35ed731c6d2fb5d (Date:   Wed Oct 19 14:40:44 2016 -0700)

Has this problem been fixed in latest releases ?
Regards,
Cédric

**Comment by sobomax** [comment]
Hi Cédric, I think this problem have been fixed here, already merged into rtpp_2_1 branch:

https://github.com/sippy/rtpproxy/commit/4cd198d355cf82c4a64437a636ebdb66ff3cac21
