### ISSUE TITLE
rtpproxy crash in bridge mode

### ISSUE THREAD

**Issue by tangshiixang** [sippy/rtpproxy#87]
in gdb:
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6905700 (LWP 42074)]
rtpp_socket_rtp_recv (self=0x7ffff000dbe8, dtime=0x0, laddr=0x0, port=0) at rtpp_socket.c:282
282         packet->rtime.mono = dtime->mono;
(gdb)  
(gdb) bt
#0  rtpp_socket_rtp_recv (self=0x7ffff000dbe8, dtime=0x0, laddr=0x0, port=0) at rtpp_socket.c:282
#1  0x000000000041d537 in rtpp_stream_drain_skt (self=0x7ffff0003968) at rtpp_stream.c:798
#2  0x0000000000412f0b in process_rtp_only (cf=cf@entry=0x7fffffffe930, ptbl=ptbl@entry=0x7ffff6904ec0, dtime=dtime@entry=0x7ffff6904eb0, drain_repeat=drain_repeat@entry=1, sender=sender@entry=0x6a4380, rsp=rsp@entry=0x6a4200)
    at rtpp_proc.c:194
#3  0x00000000004122e7 in rtpp_proc_async_run (arg=0x6a41e8) at rtpp_proc_async.c:276
#4  0x00007ffff7bc7064 in start_thread (arg=0x7ffff6905700) at pthread_create.c:309
#5  0x00007ffff71ef62d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) 

if need more details, please let me know!

**Comment by tangshiixang** [comment]
This problem occurs in the master version.  I've been downgraded to 2.1, no problem.

**Comment by sobomax** [comment]
I've added a fix, thanks for reporting!

**Comment by tangshiixang** [comment]
It can work! Thanks!
